services:
  # Frontend Static Site
  - type: web
    name: rpr-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: ./dist/rpr-verify
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend Web Service
  - type: web
    name: rpr-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: rpr-frontend
          envVarKey: RENDER_EXTERNAL_URL
